### ISSUE TITLE
QUnit is not defined error

### ISSUE THREAD

**Issue by bancer** [davidtaylorhq/qunit-puppeteer#9]
qunit-puppeteer crashes on start.

```
./node_modules/.bin/qunit-puppeteer http://localhost/tests/index.html
Error: Evaluation failed: ReferenceError: QUnit is not defined
    at <anonymous>:2:5
    at <anonymous>:12:5
    at Frame._rawEvaluate (/.../node_modules/puppeteer/lib/FrameManager.js:201:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Frame.evaluate (/.../node_modules/puppeteer/lib/FrameManager.js:175:24)
    at async /.../node_modules/qunit-puppeteer/bin/qunit-puppeteer.js:90:3
```

**Comment by xinitrc86** [comment]
same
